//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhengWeil.ExtractOil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replys
    {
        public int Id { get; set; }
        public int TopicId { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string Content { get; set; }
        public string ReplyName { get; set; }
        public string UserHostAddress { get; set; }
    
        public virtual Topics Topics { get; set; }
    }
}
